#!/bin/bash

ffmpeg -re -i $INPUT_URL \
  -c:v copy -c:a copy \
  -mpegts_pmt_start_pid 4441 -streamid 0:4442 -streamid 1:4443 \
  -metadata service_provider="SKYM TECH" -metadata service_name="Channel 1" \
  -f mpegts $OUTPUT_URL?pkt_size=1316&localaddr=$OUTPUT_INTERFACE_IP
#</dev/null > /dev/null 2>&1 & echo $! > $STREAM_PID_PATH
